hc:
  type: effort_controllers/JointTrajectoryController
  joints:
    - joint_1_s
    - joint_3_u
    - joint_2_l
    - joint_4_r
    - joint_5_b
    - joint_6_t
  gains:
    joint_1_s: { p: 15000, i: 0.01, d: 50}
    joint_2_l: { p: 15000, i: 0.01, d: 50}
    joint_3_u: { p: 15000, i: 0.01, d: 50}
    joint_4_r: { p: 15000, i: 0.01, d: 50}
    joint_5_b: { p: 10000, i: 0.01, d: 50}
    joint_6_t: { p: 5000, i: 0.01, d: 50}
    
  
